### ISSUE TITLE
unable to open ftdi device: -3 (device not found)

### ISSUE THREAD

**Issue by danbolt** [jsdf/loader64#1]
Thanks for taking the time to port this program to macOS and post it on GitHub.

I've built and installed on macOS 10.15.4 with Xcode Version 11.5 (11E608c). When I build a rom with the Nintendo 64 SDK (eg: NuSystem example `nu1`) and attempt to run `loader64` I get the following error message.
```
$ loader64 -v --write --file ./nu1.n64 
being verbose
unable to open ftdi device: -3 (device not found)
```

I've have the EverDrive 64 X7 started up and on the main screen. Is there anything I need to be running on the EverDrive side to send/receive serial messages over USB?

Thanks!

**Comment by jsdf** [comment]
You shouldn't need to do anything other than boot to the menu screen of the Everdrive.

I haven't tested it with an Everdrive X7 (I have a V3) so I'm not sure if there's anything different about the way it presents itself (eg. if the usb product id is the same) but at the very least you should be able to locate it in the macOS System Report, where it should appear under 'USB' with a name like FT245R USB FIFO'.

Are you seeing a device like this? And if so, what is the vendor ID and product ID?

<img width="911" alt="Screen Shot 2020-06-14 at 12 51 10 PM" src="https://user-images.githubusercontent.com/1232587/84599135-c637b880-ae3d-11ea-8b49-5c8e57baffee.png">

**Comment by danbolt** [comment]
Hey @jsdf  sorry about the long wait. To give an update, the issue was due to a faulty MicroUSB cable. After switching to a better-quality one, the FTDI advice appeared.
